baseURL = 'https://rayvert64.github.io'
title = 'Philippe(Adora) Boutin'
theme = "hugo.386"

[languages]
  [languages.en]
    title = "My AI Website"
    languageName = "Eng"
    contentDir = "content/en"
    weight = 1

  [languages.fr]
    title = "Mon site Web IA"
    languageName = "Fr"
    contentDir = "content/fr"
    weight = 2

  [languages.nb]
    title = "Min nettside AI"
    languageName = "Nb"
    contentDir = "content/nb"
    weight = 3

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "opinions"
    name = "Opinions/Philosophies"
    url = "/opinions/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 3